import { ENGINE_REF } from "./config.js";

export function mobileWorkflow(requestId) {
  let names = null;
  if (requestId !== undefined) {
    if (typeof requestId !== 'string' || !/^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$/i.test(requestId)) {
      throw new Error('A valid request UUID is required for a scoped caller');
    }
    const prefix = 'FLEXFACTOR_' + requestId.replaceAll('-', '').toUpperCase() + '_';
    names = {steering: prefix + 'STEERING_KEY', openai: prefix + 'OPENAI_API_KEY', anthropic: prefix + 'ANTHROPIC_API_KEY'};
  }
  // The default-branch file registers workflow_dispatch. Actual app requests
  // execute a verified, request-specific tag with only literal secret names.
  // A manual run of the registration file has no steering credential and fails.
  const binding = (name, fallback) => !name ? '""' : '${{ secrets.' + name + (fallback ? ' || secrets.' + fallback : '') + ' }}';
  return [
    "name: FlexFactor Mobile",
    "",
    "run-name: \"FlexFactor ${{ inputs.mode }} · ${{ inputs.request_id }}\"",
    "",
    "on:",
    "  workflow_dispatch:",
    "    inputs:",
    "      request_id:",
    "        required: true",
    "        type: string",
    "      mode:",
    "        required: true",
    "        type: choice",
    "        options: [refactor, scout, audit, prodready]",
    "      provider:",
    "        required: true",
    "        type: choice",
    "        options: [auto]",
    "      target_ref:",
    "        required: true",
    "        type: string",
    "      file:",
    "        required: false",
    "        type: string",
    "      goal:",
    "        required: false",
    "        type: string",
    "      guidance:",
    "        required: false",
    "        type: string",
    "      scout_apply:",
    "        required: true",
    "        type: boolean",
    "      max_cost:",
    "        required: true",
    "        type: string",
    "      threshold:",
    "        required: true",
    "        type: string",
    "      max_iterations:",
    "        required: true",
    "        type: string",
    "      steering_release_id:",
    "        required: true",
    "        type: string",
    "      steering_secret_name:",
    "        required: true",
    "        type: string",
    "      openai_secret_name:",
    "        required: false",
    "        type: string",
    "      anthropic_secret_name:",
    "        required: false",
    "        type: string",
    "",
    "permissions:",
    "  actions: read",
    "  copilot-requests: write",
    "  contents: write",
    "  issues: write",
    "  pull-requests: write",
    "",
    "jobs:",
    "  flexfactor:",
    `    uses: buckeye7066/flexfactor/.github/workflows/mobile-run.yml@${ENGINE_REF}`,
    "    with:",
    "      request_id: ${{ inputs.request_id }}",
    "      steering_release_id: ${{ inputs.steering_release_id }}",
    "      steering_secret_name: ${{ inputs.steering_secret_name }}",
    "      mode: ${{ inputs.mode }}",
    "      provider: ${{ inputs.provider }}",
    "      target_repository: ${{ github.repository }}",
    "      target_ref: ${{ inputs.target_ref }}",
    "      file: ${{ inputs.file }}",
    "      goal: ${{ inputs.goal }}",
    "      guidance: ${{ inputs.guidance }}",
    "      scout_apply: ${{ inputs.scout_apply }}",
    "      max_cost: ${{ inputs.max_cost }}",
    "      threshold: ${{ inputs.threshold }}",
    "      max_iterations: ${{ inputs.max_iterations }}",
    "    secrets:",
    `      STEERING_PRIVATE_KEY: ${binding(names?.steering)}`,
    `      OPENAI_API_KEY: ${binding(names?.openai, "OPENAI_API_KEY")}`,
    `      ANTHROPIC_API_KEY: ${binding(names?.anthropic, "ANTHROPIC_API_KEY")}`,
    "",
  ].join("\n");
}
